// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8-fPLs0N5gejwlILXPM4Uc6o4C53OmDs',
    appId: '1:426478684636:web:9dc26165fbcb586adda719',
    messagingSenderId: '426478684636',
    projectId: 'flutterauthtest-79e2a',
    authDomain: 'flutterauthtest-79e2a.firebaseapp.com',
    storageBucket: 'flutterauthtest-79e2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP4SvMAO7rpLqoFwfzc7rebn930P55lXI',
    appId: '1:426478684636:android:7b9dcb9d2437370adda719',
    messagingSenderId: '426478684636',
    projectId: 'flutterauthtest-79e2a',
    storageBucket: 'flutterauthtest-79e2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Ox31lMm5SZmXbHu-t0D6uHZ9ld8vcR8',
    appId: '1:426478684636:ios:eef565a720d6a21ddda719',
    messagingSenderId: '426478684636',
    projectId: 'flutterauthtest-79e2a',
    storageBucket: 'flutterauthtest-79e2a.appspot.com',
    iosClientId: '426478684636-2thr9llot4doepqla2f74kqsb9u2s5j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Ox31lMm5SZmXbHu-t0D6uHZ9ld8vcR8',
    appId: '1:426478684636:ios:eef565a720d6a21ddda719',
    messagingSenderId: '426478684636',
    projectId: 'flutterauthtest-79e2a',
    storageBucket: 'flutterauthtest-79e2a.appspot.com',
    iosClientId: '426478684636-2thr9llot4doepqla2f74kqsb9u2s5j9.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
